### ISSUE TITLE
Alias or nickname

### ISSUE THREAD

**Issue by cheoAlejo** [tleish/redmine_remote_revision_url#1]
This plugin is great. It's right what i was looking for. Our repos are at a gitlab instance and it's far better to review them at gitlab's than at redmine's, so this plugin is very useful, and the option to open them in new window is perfect.

I have a little issue, our domain name is a little long, it would be nice to supply an optional alias to the repo url and show the alias instead of the domain.

**_Long link:_**
![2015-06-07 09_56_34-_ - repo - pruebas - delfin redmine](https://cloud.githubusercontent.com/assets/10518807/8024612/beae5eba-0cfe-11e5-8455-1c9287276404.png)

**_Short alias:_**
![sin titulo-1](https://cloud.githubusercontent.com/assets/10518807/8024619/db023730-0cfe-11e5-80f1-2193cfcbd52c.png)

**Comment by tleish** [comment]
Glad you link the plugin.  I thought about the ability to add an alias, but wasn't sure if others would want it.

I've now added the following:
1. Custom Link Text configured with each repository.
2. Global configuration to Replace the Redmine Revision Links completely (instead of adding additional link).

See README for more details.

Thanks for the feedback.

**Comment by cheoAlejo** [comment]
Excellent. Thanks for the solution.

**Comment by tleish** [comment]
@cheoAlejo, FYI found a few bugs, one if which was significant.  I suggest you update to the latest if you haven't already.
